---
- name: Disable SSH rlogin
  hosts: node1
  become: yes
  tasks:
  - name: edit /etc/ssh/sshd_config
    replace:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin yes'
      replace: 'PermitRootLogin no'
      backup: yes
    notify: restart sshd  

  handlers:
  - name: restart sshd
    service:
      name: sshd
      state: restarted
...
